export const ACTIONTABSTATE = {
  "toggle-grid": true,
  "toggle-shown-layout-grids": true,
  "toggle-show-masks": true,
  "toggle-show-artboard-outlines": true,
  "toggle-rulers": true,
  "toggle-sidebar": true,
  "toggle-ui": true,
  "toggle-outlines": true,
  "toggle-layers": true,
  "toggle-publish": true,
  "toggle-library": true,
  "toggle-pixel-preview": true,
  "toggle-checkerboard": true,
  "zoom-in": true,
  "zoom-out": true,
  "zoom-reset": true,
  "zoom-to-fit": true,
  "zoom-to-selection": true,
  "next-artboard": true,
  "previous-artboard": true,
};

export const ACTIONFILEBROWSERSTATE = {
  "toggle-grid": false,
  "toggle-shown-layout-grids": false,
  "toggle-show-masks": false,
  "toggle-show-artboard-outlines": false,
  "toggle-rulers": false,
  "toggle-sidebar": false,
  "toggle-ui": false,
  "toggle-outlines": false,
  "toggle-layers": false,
  "toggle-publish": false,
  "toggle-library": false,
  "toggle-pixel-preview": false,
  "toggle-checkerboard": false,
  "zoom-in": false,
  "zoom-out": false,
  "zoom-reset": false,
  "zoom-to-fit": false,
  "zoom-to-selection": false,
  "next-artboard": false,
  "previous-artboard": false,
};

export const INITACTIONINITSTATE = {
  newFile: true,
  openFileBrowser: true,
  reopenClosedTab: true,
  closeTab: true,
  "save-as": false,
  "export-selected-exportables": false,
  undo: true,
  redo: true,
  "paste-over-selection": false,
  "toggle-dropper": false,
  "set-default-style": false,
  "copy-properties": false,
  "paste-properties": false,
  selectAll: false,
  "deselect-all": false,
  "select-inverse": false,
  "select-same-style": false,
  "select-same-fill": false,
  "select-same-stroke": false,
  "select-same-effect": false,
  "select-same-text": false,
  "select-same-font": false,
  "select-same-instance": false,
  "toggle-grid": false,
  "toggle-shown-layout-grids": false,
  "toggle-show-masks": false,
  "toggle-show-artboard-outlines": false,
  "toggle-rulers": false,
  "toggle-sidebar": false,
  "toggle-ui": false,
  "toggle-outlines": false,
  "toggle-layers": false,
  "toggle-publish": false,
  "toggle-library": false,
  "toggle-pixel-preview": false,
  "toggle-checkerboard": false,
  "zoom-in": false,
  "zoom-out": false,
  "zoom-reset": false,
  "zoom-to-fit": false,
  "zoom-to-selection": false,
  "scale-normal": false,
  "scale-inc0.1": false,
  "scale-dic0.1": false,
  "scale-inc0.05": false,
  "scale-dic0.05": false,
  "next-artboard": false,
  "previous-artboard": false,
  "group-selection": false,
  "ungroup-selection": false,
  "frame-selection": false,
  "mask-selection": false,
  "create-symbol": false,
  "find-symbol": false,
  "reset-symbol": false,
  "detach-instance": false,
  "resize-to-fit": false,
  "toggle-frame-clipping": false,
  "bring-to-front": false,
  "bring-forward": false,
  "send-backward": false,
  "send-to-back": false,
  "flip-horizontal": false,
  "flip-vertical": false,
  "rotate-180": false,
  "rotate-90-counterclockwise": false,
  "rotate-90-clockwise": false,
  "flatten-selection": false,
  "outline-stroke": false,
  "live-boolean-union": false,
  "live-boolean-subtract": false,
  "live-boolean-intersect": false,
  "live-boolean-xor": false,
  "duplicate-in-place": false,
  "delete-selection": false,
  "convert-to-raster": false,
  "toggle-shown-for-selected-nodes": false,
  "toggle-locked-for-selected-nodes": false,
  "hide-sibling-layers": false,
  "collapse-layers": false,
  "remove-fill": false,
  "remove-stroke": false,
  "swap-fill-and-stroke": false,
  "join-selection": false,
  "smooth-join-selection": false,
  "delete-and-heal-selection": false,
  "text-toggle-bold": false,
  "text-toggle-italic": false,
  "text-toggle-underline": false,
  "text-toggle-strikethrough": false,
  "text-original-case": false,
  "text-upper-case": false,
  "text-lower-case": false,
  "round-to-pixels": false,
  "align-left": false,
  "align-horizontal-center": false,
  "align-right": false,
  "align-top": false,
  "align-vertical-center": false,
  "align-bottom": false,
  "pack-horizontal": false,
  "pack-vertical": false,
  "distribute-horizontal-spacing": false,
  "distribute-vertical-spacing": false,
  "distribute-left": false,
  "distribute-horizontal-center": false,
  "distribute-right": false,
  "distribute-top": false,
  "distribute-vertical-center": false,
  "distribute-bottom": false,
};

export const PROPS_WITH_COLOR = [
  "color",
  "backgroundColor",
  "fill",
  "stroke",
  "borderBottomColor",
  "borderRightColor",
  "borderLeftColor",
  "borderTopColor",
  "boxShadow",
];

export const DEFAULT_PALETTE: Themes.Palette = {
  panel: "#262829",
  panelRowOnHover: "#202122",
  panelRowActive: "#36393c",
  panelRowChildActive: "#2f3132",
  panelDivider: "#36383a",
  text: "#C1C5C9",
  textCode: "#dcdee0",
  textActive: "#FFFFFF",
  textDisabled: "#818688",
  textDisabledRowActive: "#777c7e",
  textComponent: "#a694ff",
  textComponentDisabled: "#5f4fb0",
  textComponentDisabledRowActive: "#8e82c9",
  toolbarBg: "#333639",
  inputFocus: "rgba(255, 255, 255, 0.1)",
  iconButtonHover: "rgba(255, 255, 255, 0.06)",
};

export const SVG_MAP: Themes.ColorsMap = {
  'fill="#000"': 'fill="#FFF"',
};

export const SELECTORS_TO_IGNORE = [
  ".action--unfaded",
  ".action--enabled",
  ".action_option",
  ".avatar--root--2kH_E",
  ".basic_form--primaryBtn",
  ".basic_form--greenBtn",
  ".dropdown--dropdown",
  ".dropdown_menu",
  ".draggable_modal--backgroundOverlay--CPf6e",
  ".emoji-mart-anchor-selected",
  ".flyout_view--flyout",
  ".folder_view--folderTeamName",
  ".folder_view--pathSeparator",
  ".filename_view--title",
  ".filename_view--pathSeparator",
  ".filename_view--dropdownOption",
  ".fullscreen_menu--searchInput",
  ".header_modal--modalBackground",
  ".header--header--",
  ".header--settings",
  ".header--dropdownCaret",
  ".prototype--background",
  ".multilevel_dropdown--",
  ".library_item_tile--descriptionPopout",
  ".pointing_dropdown",
  ".scaling_menu--",
  ".transition_preview_pane--",
  ".top_bar--",
  ".tooltip--",
  ".toolbar_styles--activeButton",
  ".toolbar_styles--enabledButton",
  ".user_view--name",
  ".text--_whiteText",
  ".team_link--icon",
  ".zoom_menu--zoomMenu",
  ".help_widget--helpWidget",
  ".help_widget--tooltip",
  ".raw_components--iconButtonSelected",
  ".visual_bell",
  ".zoom_menu",
];
